# Generated by Django 2.2.28 on 2024-08-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('date_added', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
